commentaryAliases={
"rossi":"rashi",
"rashid":"rashi",
"rocky":"rashi",
"russia": "rashi",
"my sector": "masechta",
"random":"rambam",
"run bomb":"rambam",
"ron bomb":"rambam",
"rom bomb":"rambam",
"rom bond":"ramban",
"run robin":"ramban",
"wrong bond":"ramban",
"run bond":"ramban",
"sephora know": "seforno",
"score now": "seforno",
"for now": "seforno",
"score know": "seforno",
"so for now": "seforno",
"bother": "bava",
"father": "bava",
"baba": "bava",
"eben ezra":"ibn ezra",
"even as or":"ibn ezra",
"ibanez rough":"ibn ezra",
"evan as rough":"ibn ezra",
"eben ezra":"ibn ezra"
}
